language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get -qq install python-scipy
install:
  - pip install coveralls flake8 nose-cov

script:
  - nosetests -v --with-cov --cov-config .coveragerc --cov python
  - flake8 python
after_success:
  - coveralls
