language: python
python:
  - "2.7"

sudo: false
addons:
  apt:
    packages:
      - python-scipy

virtualenv:
  system_site_packages: true
install:
  - pip install coveralls flake8 nose-cov

script:
  - nosetests -v --with-cov --cov-config .coveragerc --cov python
  - flake8 python
after_success:
  - coveralls
